data_sources:
  faq:
    - path: "../../data_files/faq/01-04-2026-faq.yaml"
      enabled: true

  structured_docs:
    - path: "../../data_files/structured_docs/pravila_2026_example.yaml"
      enabled: true

  documents:
    - path: "../../data_files/documents/PravilaPriema2026_v1.txt"
      enabled: true