data_sources:
  faq:
    - path: "data_files/faq/faq1.yaml"
      enabled: true

  structured_docs:
    - path: "data_files/structured_docs/pravila_2026.yaml"
      enabled: false

  documents:
    - path: "data_files/documents/PravilaPriema2026_v1.txt"
      enabled: false